import { useMemo, useState } from "react";
import type { ProjectTag, TaskTemplate } from "../types";
import { generateId } from "../utils";
import { Modal } from "./Modal";

type Category = "basic" | "schedule" | "links" | "documents";
type Schedule = NonNullable<TaskTemplate["schedules"]>[number];

function BasicEditor({ template, tags, update, close }: { template: TaskTemplate; tags: ProjectTag[]; update: (changes: Partial<TaskTemplate>) => void; close: () => void }) {
  return <Modal title="基本情報を編集" onClose={close} wide><div className="template-category-window"><div className="task-template-manager-fields">
    <label>テンプレート名<input autoFocus value={template.name} onChange={(event) => update({ name: event.target.value })} /></label><label>案件タグ<select value={template.projectTagId} onChange={(event) => update({ projectTagId: event.target.value })}><option value="">案件タグなし</option>{tags.map((tag) => <option value={tag.id} key={tag.id}>{tag.name}</option>)}</select></label>
    <label>検索キーワード<input value={template.keywords.join("、")} onChange={(event) => update({ keywords: [...new Set(event.target.value.split(/[,\n、]/).map((value) => value.trim()).filter(Boolean))] })} /></label><label>タスク名<input value={template.title} onChange={(event) => update({ title: event.target.value })} /></label>
    <label className="wide">説明<textarea rows={5} value={template.description} onChange={(event) => update({ description: event.target.value })} /></label><label className="wide">次のアクション<textarea rows={3} value={template.nextAction} onChange={(event) => update({ nextAction: event.target.value })} /></label>
    <label>優先度<select value={template.priority} onChange={(event) => update({ priority: event.target.value as TaskTemplate["priority"] })}><option>A</option><option>B</option><option>C</option><option>D</option></select></label><label>タスク全体の予定工数<input type="number" min="0" step="0.25" value={template.plannedHours || ""} onChange={(event) => update({ plannedHours: Math.max(0, Number(event.target.value) || 0) })} /></label>
  </div><div className="modal-actions"><span>変更内容は自動保存されます。</span><button className="primary" onClick={close}>閉じる</button></div></div></Modal>;
}

function ScheduleEditor({ schedules, update, close }: { schedules: Schedule[]; update: (schedules: Schedule[]) => void; close: () => void }) {
  const [editing, setEditing] = useState<number | null>(null);
  const [draft, setDraft] = useState<Schedule>({ title: "", description: "", plannedHours: 0, status: "not-started" });
  const load = (index: number) => { setEditing(index); setDraft({ ...schedules[index] }); };
  const reset = () => { setEditing(null); setDraft({ title: "", description: "", plannedHours: 0, status: "not-started" }); };
  const save = () => { const next = editing === null ? [...schedules, draft] : schedules.map((item, index) => index === editing ? draft : item); update(next); reset(); };
  const scheduled = draft.startOffsetDays !== undefined;
  return <Modal title="予定テンプレートを編集" onClose={close} wide><div className="template-category-window template-schedule-window">
    <div className="template-schedule-list"><header><div><strong>タスクスケジュール</strong><small>{schedules.length}件・予定工数 {schedules.reduce((sum, item) => sum + (Number(item.plannedHours) || 0), 0)}h</small></div><button className="primary" onClick={reset}>＋ 予定を追加</button></header>{schedules.map((item, index) => <article key={index}><div><strong>{item.title || "無題の予定"}</strong><span>{item.startOffsetDays === undefined ? "日付なし" : `作成日から${item.startOffsetDays}日後から${Math.max(1, (item.endOffsetDays ?? item.startOffsetDays) - item.startOffsetDays + 1)}日間`}</span><small>{item.description || "説明なし"}・予定 {item.plannedHours || 0}h</small></div><button onClick={() => load(index)}>詳細編集</button><button className="danger-text" onClick={() => update(schedules.filter((_, i) => i !== index))}>削除</button></article>)}{!schedules.length && <p className="empty-list">予定はまだありません。</p>}</div>
    <div className="template-schedule-form"><h3>{editing === null ? "予定を追加" : "予定を編集"}</h3><div className="task-schedule-quick-form-main"><label>予定の題名<input autoFocus value={draft.title || ""} onChange={(event) => setDraft({ ...draft, title: event.target.value })} placeholder="例：資料作成" /></label><label>予定工数（時間）<input type="number" min="0" step="0.25" value={draft.plannedHours || ""} onChange={(event) => setDraft({ ...draft, plannedHours: Math.max(0, Number(event.target.value) || 0) })} placeholder="例：2" /></label><label>状態<select value="not-started" disabled><option>未着手</option></select></label></div>
      <label className="template-schedule-description">予定の説明<textarea rows={3} value={draft.description || ""} onChange={(event) => setDraft({ ...draft, description: event.target.value })} placeholder="実施内容や完了条件など" /></label>
      <div className="template-schedule-date-mode"><label><input type="radio" checked={!scheduled} onChange={() => setDraft({ ...draft, startOffsetDays: undefined, endOffsetDays: undefined })} />日付なし</label><label><input type="radio" checked={scheduled} onChange={() => setDraft({ ...draft, startOffsetDays: 0, endOffsetDays: 0 })} />タスク作成日を基準に設定</label></div>
      {scheduled && <div className="task-schedule-quick-dates"><label>開始（作成日から）<span className="template-offset-input"><input type="number" min="0" value={draft.startOffsetDays ?? 0} onChange={(event) => { const previousStart = draft.startOffsetDays ?? 0; const duration = Math.max(1, (draft.endOffsetDays ?? previousStart) - previousStart + 1); const value = Math.max(0, Number(event.target.value) || 0); setDraft({ ...draft, startOffsetDays: value, endOffsetDays: value + duration - 1 }); }} />日後から</span></label><span>・</span><label>作業日数<span className="template-offset-input"><input type="number" min="1" value={Math.max(1, (draft.endOffsetDays ?? draft.startOffsetDays ?? 0) - (draft.startOffsetDays ?? 0) + 1)} onChange={(event) => { const duration = Math.max(1, Number(event.target.value) || 1); const start = draft.startOffsetDays ?? 0; setDraft({ ...draft, endOffsetDays: start + duration - 1 }); }} />日間</span></label></div>}
      <div className="task-schedule-quick-form-actions">{editing !== null && <button onClick={reset}>キャンセル</button>}<button className="primary" onClick={save}>{editing === null ? "予定を追加" : "予定を更新"}</button></div>
    </div><div className="modal-actions"><button className="primary" onClick={close}>予定編集を閉じる</button></div>
  </div></Modal>;
}

function LinksEditor({ template, update, close }: { template: TaskTemplate; update: (changes: Partial<TaskTemplate>) => void; close: () => void }) { return <Modal title="リンクを編集" onClose={close} wide><div className="template-category-window"><div className="task-template-content-section"><header><strong>登録リンク</strong><button onClick={() => update({ links: [...template.links, { id: generateId(), label: "", url: "" }] })}>＋ リンクを追加</button></header>{template.links.map((link) => <div className="task-template-link-row" key={link.id}><input value={link.label} placeholder="表示名" onChange={(event) => update({ links: template.links.map((item) => item.id === link.id ? { ...item, label: event.target.value } : item) })} /><input value={link.url} placeholder="URL" onChange={(event) => update({ links: template.links.map((item) => item.id === link.id ? { ...item, url: event.target.value } : item) })} /><button className="danger-text" onClick={() => update({ links: template.links.filter((item) => item.id !== link.id) })}>削除</button></div>)}</div><div className="modal-actions"><button className="primary" onClick={close}>閉じる</button></div></div></Modal>; }

function DocumentsEditor({ template, update, close }: { template: TaskTemplate; update: (changes: Partial<TaskTemplate>) => void; close: () => void }) { return <Modal title="手順書・資料を編集" onClose={close} wide><div className="template-category-window"><div className="task-template-content-section">{template.documents.map((document) => <details className="task-template-document" key={document.id}><summary>{document.kind === "folder" ? "📁" : "📄"} {document.title || "無題"}</summary><label>資料名<input value={document.title} onChange={(event) => update({ documents: template.documents.map((item) => item.id === document.id ? { ...item, title: event.target.value, updatedAt: new Date().toISOString() } : item) })} /></label>{document.kind !== "folder" && <label>内容<textarea rows={9} value={document.content} onChange={(event) => update({ documents: template.documents.map((item) => item.id === document.id ? { ...item, content: event.target.value, updatedAt: new Date().toISOString() } : item) })} /></label>}</details>)}{!template.documents.length && <p className="empty-list">手順書・資料は登録されていません。</p>}</div><div className="modal-actions"><button className="primary" onClick={close}>閉じる</button></div></div></Modal>; }

function TemplateEditor({ template, tags, update, remove, close }: { template: TaskTemplate; tags: ProjectTag[]; update: (changes: Partial<TaskTemplate>) => void; remove: () => void; close: () => void }) {
  const [category, setCategory] = useState<Category | null>(null);
  const cards: Array<[Category, string, string, number | null]> = [["basic", "基本情報", "名称・案件タグ・説明・優先度・工数", null], ["schedule", "予定", "ChatTask形式で日付なし・作成日基準を設定", (template.schedules || []).length], ["links", "リンク", "関連URL・外部資料", template.links.length], ["documents", "手順書・資料", "タスク作成時に内容ごと複製", template.documents.length]];
  return <><Modal title={`テンプレートを編集：${template.name}`} onClose={close} wide><div className="template-editor-hub"><p>編集するカテゴリを選択してください。</p><div>{cards.map(([id, title, description, count]) => <button key={id} onClick={() => setCategory(id)}><span><strong>{title}</strong><small>{description}</small></span>{count !== null && <b>{count}件</b>}<i>›</i></button>)}</div><div className="modal-actions"><button className="danger-text" onClick={remove}>テンプレートを削除</button><button className="primary" onClick={close}>閉じる</button></div></div></Modal>
    {category === "basic" && <BasicEditor template={template} tags={tags} update={update} close={() => setCategory(null)} />}{category === "schedule" && <ScheduleEditor schedules={template.schedules || []} update={(schedules) => update({ schedules })} close={() => setCategory(null)} />}{category === "links" && <LinksEditor template={template} update={update} close={() => setCategory(null)} />}{category === "documents" && <DocumentsEditor template={template} update={update} close={() => setCategory(null)} />}</>;
}

export function TaskTemplateManagerModal({ templates, tags, onChange, onClose }: { templates: TaskTemplate[]; tags: ProjectTag[]; onChange: (templates: TaskTemplate[]) => void; onClose: () => void }) {
  const [query, setQuery] = useState(""); const [tagFilter, setTagFilter] = useState("all"); const [editingId, setEditingId] = useState(""); const normalized = query.trim().toLocaleLowerCase("ja");
  const visible = useMemo(() => templates.filter((template) => (tagFilter === "all" || (tagFilter === "none" ? !template.projectTagId : template.projectTagId === tagFilter)) && (!normalized || [template.name, template.title, template.description, template.nextAction, ...template.keywords].some((value) => String(value || "").toLocaleLowerCase("ja").includes(normalized)))), [templates, normalized, tagFilter]);
  const groups = useMemo(() => [...new Set(visible.map((template) => template.projectTagId || "none"))].map((id) => ({ id, name: tags.find((tag) => tag.id === id)?.name || "案件タグなし", items: visible.filter((template) => (template.projectTagId || "none") === id) })), [visible, tags]);
  const update = (id: string, changes: Partial<TaskTemplate>) => onChange(templates.map((template) => template.id === id ? { ...template, ...changes, updatedAt: new Date().toISOString() } : template)); const editing = templates.find((template) => template.id === editingId);
  const remove = (template: TaskTemplate) => { if (window.confirm(`テンプレート「${template.name}」を削除しますか？`)) { onChange(templates.filter((item) => item.id !== template.id)); setEditingId(""); } };
  return <><Modal title="タスクテンプレート管理" onClose={onClose} wide><div className="task-template-manager"><header><input autoFocus value={query} onChange={(event) => setQuery(event.target.value)} placeholder="テンプレート名・内容・キーワードで検索" /><select value={tagFilter} onChange={(event) => setTagFilter(event.target.value)}><option value="all">すべての案件タグ</option><option value="none">案件タグなし</option>{tags.map((tag) => <option value={tag.id} key={tag.id}>{tag.name}</option>)}</select><span>{visible.length}件</span></header><div className="task-template-manager-list">{groups.map((group) => <section className="task-template-group" key={group.id}><h3>{group.name}<small>{group.items.length}件</small></h3>{group.items.map((template) => <article className="task-template-card" key={template.id}><div><strong>{template.name}</strong><small>{template.title}</small></div><span>予定 {(template.schedules || []).length}件</span><span>資料 {template.documents.length}件</span><span>リンク {template.links.length}件</span><button onClick={() => setEditingId(template.id)}>編集</button></article>)}</section>)}</div><div className="modal-actions"><button className="primary" onClick={onClose}>閉じる</button></div></div></Modal>{editing && <TemplateEditor template={editing} tags={tags} update={(changes) => update(editing.id, changes)} remove={() => remove(editing)} close={() => setEditingId("")} />}</>;
}
